<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Austin Till" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Modeling, Testing, and Classification</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project2/">Modeling, Testing, and Classification</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          May 14, 2020
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<pre class="r"><code>library(carData)
library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ──────────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.0     ✓ purrr   0.3.4
## ✓ tibble  3.0.1     ✓ stringr 1.4.0
## ✓ tidyr   1.0.3     ✓ forcats 0.5.0
## ✓ readr   1.3.1</code></pre>
<pre><code>## ── Conflicts ─────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>Wong &lt;- read.csv(&quot;Wong.csv&quot;)
head(Wong)</code></pre>
<pre><code>##   X   id days duration  sex      age piq viq
## 1 1 3358   30        4 Male 20.67077  87  89
## 2 2 3535   16       17 Male 55.28816  95  77
## 3 3 3547   40        1 Male 55.91513  95 116
## 4 4 3592   13       10 Male 61.66461  59  73
## 5 5 3728   19        6 Male 30.12731  67  73
## 6 6 3790   13        3 Male 57.06229  76  69</code></pre>
<p><em>The dataset I will be working with is Wong. The dataset contains statistical information on recovery of IQ after comas of different durations for 200 subjects for a total of 331 observations. The average number of measurements per patient is 1.7. The dataset contains patient ID numbers for each patient. It also contains a variable for the number of days post coma when IQs were measured. The duration of each patient’s coma is another variable in the dataset. Characteristics of the patient include their age (in years) at the time of coma and their sex (male or female). Both a performance IQ and a verbal IQ were measured and recorded for each patient.</em></p>
<pre class="r"><code>#MANOVA
man1 &lt;- manova(cbind(days,duration,age,piq,viq)~sex, data=Wong)
summary(man1)</code></pre>
<pre><code>##            Df   Pillai approx F num Df den Df Pr(&gt;F)
## sex         1 0.023766   1.5824      5    325 0.1645
## Residuals 329</code></pre>
<p><em>For each response variable, the means of the groups are equal.</em></p>
<pre class="r"><code>#Randomization Test
Wong%&gt;%group_by(sex)%&gt;%
  summarize(means=mean(piq))%&gt;%summarize(`mean_diff:`=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `mean_diff:`
##          &lt;dbl&gt;
## 1        -2.07</code></pre>
<pre class="r"><code>rand_dist&lt;-vector()

for(i in 1:5000){
new&lt;-data.frame(piq=sample(Wong$piq),sex=Wong$sex) 
rand_dist[i]&lt;-mean(new[new$sex==&quot;Male&quot;,]$piq)-
              mean(new[new$sex==&quot;Female&quot;,]$piq)
}

{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;); abline(v = 2.07156,col=&quot;red&quot;)}</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code>mean(rand_dist&gt;2.07156 | rand_dist&lt; -2.07156)</code></pre>
<pre><code>## [1] 0.3134</code></pre>
<pre class="r"><code>t.test(data=Wong,piq~sex)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  piq by sex
## t = 0.89608, df = 95.285, p-value = 0.3725
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.517771  6.660891
## sample estimates:
## mean in group Female   mean in group Male 
##             89.18310             87.11154</code></pre>
<p><em>HO: Mean performance IQ is the same for males and females after comas. HA: Mean performance IQ is different for males and females after comas. The actual mean difference between males and females performance IQ scores was 2.07156. The probability of getting a mean difference as big as 2.07156 under the created null distribution of randomized data is 0.3022 (tw-tailed p-value). Since the p-value is not less than 0.05, we cannot reject the null hypothesis that mean performance IQ is the same for males and females after a coma.</em></p>
<pre class="r"><code>#Linear Regression
library(sandwich)
library(lmtest)</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code>#Coefficient Estimates
Wong$age_c &lt;- Wong$age - mean(Wong$age)
Wong$days_c &lt;- Wong$days - mean(Wong$days)
Wong$duration_c &lt;- Wong$duration - mean(Wong$duration)
fit &lt;- lm(viq ~ sex*duration_c, data=Wong)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = viq ~ sex * duration_c, data = Wong)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -30.876 -10.323  -1.022  10.116  37.043 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         92.8614     1.7788  52.205   &lt;2e-16 ***
## sexMale              2.2471     1.9796   1.135   0.2572    
## duration_c          -0.2965     0.1268  -2.337   0.0200 *  
## sexMale:duration_c   0.3127     0.1305   2.396   0.0171 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.99 on 327 degrees of freedom
## Multiple R-squared:  0.01777,    Adjusted R-squared:  0.008762 
## F-statistic: 1.972 on 3 and 327 DF,  p-value: 0.118</code></pre>
<pre class="r"><code>#Regression Plot
ggplot(Wong, aes(x=duration_c, y=viq,group=sex))+geom_point(aes(color=sex))+
geom_smooth(method=&quot;lm&quot;,formula=y~1,se=F,fullrange=T,aes(color=sex))</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values

#Checking Assumptions
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<pre class="r"><code>bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 4.0379, df = 3, p-value = 0.2574</code></pre>
<pre class="r"><code>ggplot()+geom_histogram(aes(resids),bins=20)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-4-3.png" width="672" /></p>
<pre class="r"><code>ggplot()+geom_qq(aes(sample=resids))+geom_qq_line(aes(sample=resids), color=&#39;red&#39;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-4-4.png" width="672" /></p>
<pre class="r"><code>ks.test(resids, &quot;pnorm&quot;, sd=sd(resids))</code></pre>
<pre><code>## Warning in ks.test(resids, &quot;pnorm&quot;, sd = sd(resids)): ties should not be present
## for the Kolmogorov-Smirnov test</code></pre>
<pre><code>## 
##  One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.043174, p-value = 0.5679
## alternative hypothesis: two-sided</code></pre>
<pre class="r"><code>#Normal-theory SEs
summary(fit)$coef[,1:2]</code></pre>
<pre><code>##                      Estimate Std. Error
## (Intercept)        92.8613805  1.7787738
## sexMale             2.2470821  1.9795757
## duration_c         -0.2964586  0.1268495
## sexMale:duration_c  0.3127033  0.1304839</code></pre>
<pre class="r"><code># Robust SEs
coeftest(fit,vcov=vcovHC(fit))[,1:2]</code></pre>
<pre><code>##                      Estimate Std. Error
## (Intercept)        92.8613805  1.5935258
## sexMale             2.2470821  1.8185382
## duration_c         -0.2964586  0.1099487
## sexMale:duration_c  0.3127033  0.1150825</code></pre>
<pre class="r"><code># R^2 Variability
sum((fitvals-mean(Wong$viq))^2)/sum((Wong$viq-mean(Wong$viq))^2)</code></pre>
<pre><code>## [1] 0.01777285</code></pre>
<pre class="r"><code>#Bootstrapped SEs
samp_distn&lt;-replicate(5000, {
boot_dat &lt;- sample_frac(Wong, replace=T)
fit &lt;- lm(viq ~ sex*duration_c, data=boot_dat)
coef(fit)
})

samp_distn %&gt;% t %&gt;% as.data.frame %&gt;% summarize_all(sd)</code></pre>
<pre><code>##   (Intercept)  sexMale duration_c sexMale:duration_c
## 1    1.534826 1.756339  0.1060249           0.110573</code></pre>
<p><em>Predicted verbal IQ for females who were in a coma for an average amount of days is 92.86. For people with an average duration of days in coma, males have a predicted verbal IQ that is 2.25 higher than females. Females show a decrease verbal IQ of 0.30 for every day increase in coma duration on average. The slope for duration of coma in days on verbal IQ is 0.31 higher for males compared to females. The linear relationship between verbal IQ, sex, and duration of coma appears violated. The histogram doesn’t appear very normally distributed and many points aren’t on the line of the Q-Q plot indicating that residuals may not be normally distributed. Equal variance appears to be violated as well due to the clustering of data points on the scatter plot. However, both the Breusch-Pagan and the KS test do not have significant p-values, meaning the distributions are normal. The corrected standard errors robust to violations of homoskedasticity get smaller potentially because normality was already met so the robust standard errors are smaller and more efficient. The proportion of variation in the response variable (verbal IQ) explained by the overall model is is 0.018. The bootstrapped standard errors were lower than both the normal standard errors and the robust standard errors.</em></p>
<pre class="r"><code>#Logistic Regression

#Interpreting Coefficients
Wong$sex &lt;- as.factor(Wong$sex)
fit1 &lt;- glm(sex~piq+viq+duration,data = Wong,family = binomial(link = &quot;logit&quot;))
coeftest(fit1)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##               Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  1.0168508  0.9675667  1.0509   0.2933
## piq         -0.0150218  0.0124042 -1.2110   0.2259
## viq          0.0151453  0.0131614  1.1507   0.2498
## duration     0.0146145  0.0095379  1.5323   0.1255</code></pre>
<pre class="r"><code>exp(coef(fit1))</code></pre>
<pre><code>## (Intercept)         piq         viq    duration 
##   2.7644750   0.9850904   1.0152606   1.0147218</code></pre>
<pre class="r"><code>#Confusion Matrix
probs&lt;-predict(fit1,type=&quot;response&quot;)
table(predict=as.numeric(probs&gt;.5),truth=Wong$sex)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict Female Male Sum
##     1       71  260 331
##     Sum     71  260 331</code></pre>
<pre class="r"><code>260/331 #Accuracy</code></pre>
<pre><code>## [1] 0.7854985</code></pre>
<pre class="r"><code>260/260 #Sensitivity (TPR)</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>0 #Specificity (TNR)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>260/331 #Precision (PPV)</code></pre>
<pre><code>## [1] 0.7854985</code></pre>
<pre class="r"><code>#Density Plot
Wong$logit&lt;-predict(fit1)
Wong$outcome&lt;-factor(Wong$sex,levels=c(&quot;Male&quot;,&quot;Female&quot;))
ggplot(Wong,aes(logit, fill=sex))+geom_density(alpha=.3)+
  geom_vline(xintercept=0,lty=2)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>#ROC Plot and AUC
library(plotROC)
library(pROC)</code></pre>
<pre><code>## Type &#39;citation(&quot;pROC&quot;)&#39; for a citation.</code></pre>
<pre><code>## 
## Attaching package: &#39;pROC&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:plotROC&#39;:
## 
##     ggroc</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     cov, smooth, var</code></pre>
<pre class="r"><code>ROCplot&lt;-ggplot(Wong)+geom_roc(aes(d=sex,m=probs), n.cuts=0)+
geom_segment(aes(x=0,xend=1,y=0,yend=1),lty=2)
ROCplot</code></pre>
<pre><code>## Warning in verify_d(data$d): D not labeled 0/1, assuming Female = 0 and Male =
## 1!</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>## Warning in verify_d(data$d): D not labeled 0/1, assuming Female = 0 and Male =
## 1!</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.5760834</code></pre>
<pre class="r"><code>view(Wong)

# GIVE IT PREDICTED PROBS AND TRUTH LABELS, RETURNS VARIOUS DIAGNOSTICS

class_diag&lt;-function(probs,truth){
  
  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  prediction&lt;-ifelse(probs&gt;.5,1,0)
  acc=mean(truth==prediction)
  sens=mean(prediction[truth==1]==1)
  spec=mean(prediction[truth==0]==0)
  ppv=mean(truth[prediction==1]==1)
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}


Wong$outcome&lt;-NULL
class_diag(probs,Wong$sex)</code></pre>
<pre><code>##         acc sens spec       ppv       auc
## 1 0.7854985    1    0 0.7854985 0.5760834</code></pre>
<pre class="r"><code>#10-fold CV
set.seed(1234)
k=10

data&lt;-Wong[sample(nrow(Wong)),] #randomly order rows
folds&lt;-cut(seq(1:nrow(Wong)),breaks=k,labels=F) #create folds

diags&lt;-NULL
for(i in 1:k){
  ## Create training and test sets
  train&lt;-data[folds!=i,] 
  test&lt;-data[folds==i,]
  truth&lt;-test$sex
  
  ## Train model on training set
  fit&lt;-glm(sex~piq+viq+duration,data=train,family=&quot;binomial&quot;)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  
  ## Test model on test set (save all k results)
  diags&lt;-rbind(diags,class_diag(probs,truth))
}


summarize_all(diags,mean)</code></pre>
<pre><code>##         acc sens spec       ppv       auc
## 1 0.7853832    1    0 0.7853832 0.5614056</code></pre>
<p><em>Odds of being a male for performance IQ=0, verbal IQ=0, and duration of coma=0 is 2.76. Controlling for verbal IQ and duration of coma, for every addition performance IQ point, odds of being a male is 0.99 times odds of being a female. Controlling for performance IQ and duration of coma, for every additional verbal IQ point, odds of being a male is 1.02 higher than odds of being a female. Controlling for performance IQ and verbal IQ, for every one day increase in duration of coma, odds of being a male are 1.01 odds of being a female. The model predicted that every observation was male. The accuracy, proportion of correctly classified cases, was 0.79, the sensitivity (true positive rate) was 1.00. This is the proportions of males correctly classified. The specificity (true negative rate) was 0.00, the proportion of females correctly classified. The precision (positive predictive value) was 0.79, the proportion of classified males that actually were males. The AUC is 0.58, the model of performance IQ, verbal IQ, and duration of coma are bad at predicting whether or not the patient is male or female. After performing a 10-fold CV, the out of sample accuracy is 0.79, sensitivity is 1, specificity is 0, ppv is 0.79, and AUC is 0.55. The AUC decreased from 0.58 to 0.55, not a large difference but the in-sample model was already a bad predictor of whether a patient was male or female.</em></p>
<pre class="r"><code>#LASSO Regression
library(glmnet)</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loaded glmnet 3.0-2</code></pre>
<pre class="r"><code>y &lt;- as.matrix(Wong$sex)
x &lt;- model.matrix(sex~.,data = Wong)[,-1]

cv &lt;- cv.glmnet(x,y,family=&quot;binomial&quot;)
lasso &lt;- glmnet(x,y,family = &quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 12 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                       s0
## (Intercept) 1.298002e+00
## X           .           
## id          .           
## days        .           
## duration    .           
## age         .           
## piq         .           
## viq         .           
## age_c       .           
## days_c      .           
## duration_c  .           
## logit       3.613730e-16</code></pre>
<p><em>None of the variables where retained from the LASSO regression. This means that none of the variables in this dataset are not significant predictors of sex.</em></p>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
